#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# set the cursor
xsetroot -cursor_name left_ptr
# set Dvorak keyboard layout
setxkbmap us -variant dvorak
export LANG=en_US.UTF-8

# add third pointer goodness
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 1
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 2 
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Timeout" 200
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 6 7 4 5
xset -b # No system beep
setleds -caps

xrdb -merge ~/.config/X11/xresources

# bind XF86 and other key maps
xbindkeys -f ~/.config/X11/xbindkeysrc
# change caps lock to mod4 key
xmodmap -e "clear Lock"       
xmodmap -e "keycode 66 = Hyper_L"
xmodmap -e "add mod4 = Hyper_L" 

# start composite manager
# xcompmgr -n &

feh --randomize --bg-fill ~/Pictures/wallpapers/*
#date +"%A"

# start Window manager
exec xmonad
# exec gnome-session
# exec startkde
# exec startxfce4
# exec enlightenment_start 
# exec awesome

# Start a simple notification Daemon
exec dunst -config ~/.config/X11/dunstrc

